# Malnati/code-literal-sentinel@v2.0.1
name: "Code Literal Sentinel"
description: "Varredura agressiva de literais. Gera um relatório e abre uma PR dedicada para análise."
author: "Ricardo Malnati"

branding:
  icon: "eye"
  color: "orange"

inputs:
  token:
    description: "GitHub token (com permissões de escrita) para criar Branches e PRs."
    required: true
  file_extensions:
    description: "Regex de extensões para varrer."
    required: false
    default: "ts|js|jsx|tsx|java|py|go|cs|php|sh|json|yaml|yml"
  exclude_patterns:
    description: "Regex de caminhos para ignorar."
    required: false
    default: "node_modules|dist|build|.git"
  report_dir:
    description: "Diretório onde os relatórios serão salvos."
    required: false
    default: "reports/code-literal-sentinel"

outputs:
  result_json:
    description: "JSON contendo diagnóstico, contagens e Link da PR de relatório."
    value: ${{ steps.generate_output.outputs.json_payload }}

runs:
  using: "composite"
  steps:
    # ------------------------------------------------------------------
    # STEP 0: DIAGNÓSTICO
    # ------------------------------------------------------------------
    - id: debug_inputs
      shell: bash
      env:
        EXTS: ${{ inputs.file_extensions }}
        DIR: ${{ inputs.report_dir }}
      run: |
        echo "::group::🔍 Step 0: Sentinel Configuration"
        echo "---------------------------------------------------------------"
        echo "👁️  Code Literal Sentinel (Report PR Mode)"
        echo "---------------------------------------------------------------"
        echo "⚙️  Configuração:"
        echo "    - Extensões: .($EXTS)"
        echo "    - Destino:   $DIR/<timestamp>.md"
        echo "---------------------------------------------------------------"
        echo "::endgroup::"

    # ------------------------------------------------------------------
    # STEP 0.5: VERIFICAÇÃO DE ESCRITA
    # ------------------------------------------------------------------
    - id: check_perms
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
      run: |
        echo "::group::🔐 Step 0.5: Permission Check"
        if [ -z "$TOKEN" ]; then
           echo "❌ Token não fornecido."
           exit 1
        fi
        echo "✅ Token presente. A validação final ocorrerá no 'git push'."
        echo "   Requisito: 'contents: write' e 'pull-requests: write'."
        echo "::endgroup::"

    # ------------------------------------------------------------------
    # STEP 1: SCAN E GERAÇÃO DE ARQUIVO
    # ------------------------------------------------------------------
    - id: scan
      shell: bash
      env:
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        EXTS: ${{ inputs.file_extensions }}
        EXCLUDE: ${{ inputs.exclude_patterns }}
        REPORT_DIR: ${{ inputs.report_dir }}
      run: |
        set -euo pipefail
        
        echo "🔎 Iniciando varredura..."
        TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
        FULL_PATH="./$REPORT_DIR/$TIMESTAMP.md"
        mkdir -p "$REPORT_DIR"

        # 1. Listar arquivos
        FILES=$(git diff --name-only --diff-filter=ACMRTUXB "$BASE_SHA" "$HEAD_SHA" \
          | grep -E "\.($EXTS)$" \
          | grep -vE "$EXCLUDE" || true)

        if [ -z "$FILES" ]; then
          echo "NO_FILES" > /tmp/scan_status
          echo "0" > /tmp/scan_count
          exit 0
        fi

        # 2. Grep Agressivo
        PATTERN="\"[^\"]{2,}\"|'[^']{2,}'"
        
        # Gerar conteúdo Markdown
        echo "# Relatório de Literais Hardcoded" > "$FULL_PATH"
        echo "**Data:** $TIMESTAMP" >> "$FULL_PATH"
        echo "**Origem:** SHA $HEAD_SHA" >> "$FULL_PATH"
        echo "" >> "$FULL_PATH"
        echo "## 🔍 Evidências Brutas" >> "$FULL_PATH"
        echo "\`\`\`text" >> "$FULL_PATH"
        echo "$FILES" | xargs -r grep -HnE "$PATTERN" >> "$FULL_PATH" || true
        echo "\`\`\`" >> "$FULL_PATH"

        # Verifica contagem
        COUNT=$(grep -cE "$PATTERN" "$FULL_PATH" || true)
        
        if [ "$COUNT" -gt "0" ]; then
           echo "FOUND" > /tmp/scan_status
           echo "$COUNT" > /tmp/scan_count
           echo "path=$FULL_PATH" >> "$GITHUB_OUTPUT"
        else
           echo "CLEAN" > /tmp/scan_status
           echo "0" > /tmp/scan_count
           rm "$FULL_PATH"
        fi

    # ------------------------------------------------------------------
    # STEP 2: CRIAR BRANCH E PR DE RELATÓRIO (SIMPLIFICADO)
    # ------------------------------------------------------------------
    - id: create_pr
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        REPORT_PATH: ${{ steps.scan.outputs.path }}
        HEAD_REF: ${{ github.event.pull_request.head.ref }}
        PR_NUM: ${{ github.event.pull_request.number }}
      run: |
        set -euo pipefail
        
        STATUS=$(cat /tmp/scan_status)
        PR_URL=""
        
        if [ "$STATUS" == "FOUND" ]; then
           echo "🚀 Preparando Pull Request de Relatório..."
           
           git config user.name "sentinel-bot"
           git config user.email "sentinel-bot@users.noreply.github.com"
           
           # Nova Nomenclatura Padronizada: <origem>/audit/code-literal-sentinel
           # Removemos timestamp da branch para permitir atualização da mesma PR de report se rodar 2x
           REPORT_BRANCH="${HEAD_REF}/audit/code-literal-sentinel"
           
           # Checkout e criação da branch
           git checkout "$HEAD_REF"
           # -B força a criação ou reset da branch se ela já existir
           git checkout -B "$REPORT_BRANCH"
           
           git add "$REPORT_PATH"
           git commit -m "docs(sentinel): add literal scan report [skip ci]"
           
           # Push forçado para atualizar a branch de relatório se já existir
           git push -f origin "$REPORT_BRANCH"
           
           echo "📡 Criando/Atualizando PR..."
           
           # Tenta criar a PR. Se já existir, o comando falha graciosamente, mas recuperamos a URL
           # || true garante que o script não quebre se a PR já existir
           gh pr create \
             --base "$HEAD_REF" \
             --head "$REPORT_BRANCH" \
             --title "🛡️ Sentinel Audit: PR #$PR_NUM" \
             --body "Relatório automático de literais hardcoded. Branch de origem: \`$HEAD_REF\`." || true
             
           # Recupera a URL da PR (seja nova ou existente)
           PR_URL=$(gh pr view "$REPORT_BRANCH" --json url -q .url)
           
           echo "✅ PR Disponível: $PR_URL"
        fi
        
        echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"

    # ------------------------------------------------------------------
    # STEP 3: GERAR JSON FINAL
    # ------------------------------------------------------------------
    - id: generate_output
      shell: bash
      env:
        PR_URL: ${{ steps.create_pr.outputs.pr_url }}
      run: |
        set -euo pipefail
        
        STATUS=$(cat /tmp/scan_status)
        COUNT=$(cat /tmp/scan_count)
        
        if [ "$STATUS" == "FOUND" ]; then
           MSG="Literais detectados ($COUNT)."
           GUIDE="Relatório disponível em: **[Ver PR de Auditoria]($PR_URL)**."
           COLOR="#dbab09"
        elif [ "$STATUS" == "CLEAN" ]; then
           MSG="Código limpo."
           GUIDE="Nenhum literal hardcoded detectado."
           COLOR="#3fb950"
        else
           MSG="Ignorado."
           GUIDE="Sem alterações em arquivos monitorados."
           COLOR="#8b949e"
        fi

        jq -n \
          --arg status "$STATUS" \
          --arg count "$COUNT" \
          --arg msg "$MSG" \
          --arg guide "$GUIDE" \
          --arg url "$PR_URL" \
          --arg color "$COLOR" \
          '{
            analysis: {
              status: $status,
              total_findings: ($count | tonumber),
              report_pr_url: $url
            },
            ui: {
              message: $msg,
              guidance: $guide,
              color: $color
            }
          }' > /tmp/output_payload.json

        JSON_LINE=$(jq -c . /tmp/output_payload.json)
        echo "json_payload=$JSON_LINE" >> "$GITHUB_OUTPUT"
