# Malnati/code-literal-sentinel@v2.1.1
name: "Code Literal Sentinel"
description: "Varredura agressiva de literais. Gera um relatório e abre uma PR dedicada para análise."
author: "Ricardo Malnati"

branding:
  icon: "eye"
  color: "orange"

inputs:
  token:
    description: "GitHub token."
    required: true
  file_extensions:
    description: "Regex de extensões."
    required: false
    default: "ts|js|jsx|tsx|java|py|go|cs|php|sh|json|yaml|yml"
  exclude_patterns:
    description: "Regex de ignorados."
    required: false
    default: "node_modules|dist|build|.git|reports/code-literal-sentinel"
  report_dir:
    description: "Diretório dos relatórios."
    required: false
    default: "reports/code-literal-sentinel"

outputs:
  result_json:
    description: "JSON de diagnóstico."
    value: ${{ steps.generate_output.outputs.json_payload }}

runs:
  using: "composite"
  steps:
    # ------------------------------------------------------------------
    # STEP 0: DIAGNÓSTICO
    # ------------------------------------------------------------------
    - id: debug_inputs
      shell: bash
      env:
        EXTS: ${{ inputs.file_extensions }}
        DIR: ${{ inputs.report_dir }}
      run: |
        echo "::group::🔍 Step 0: Sentinel Configuration (v2.1.1)"
        echo "⚙️  Extensions: .($EXTS)"
        echo "⚙️  Target Dir: $DIR"
        echo "::endgroup::"

    # ------------------------------------------------------------------
    # STEP 0.1: CIRCUIT BREAKER (ROBUSTO)
    # Usamos a expressão do GitHub para pular TUDO se for branch de auditoria
    # ------------------------------------------------------------------
    - id: circuit_breaker
      shell: bash
      # AQUI ESTÁ A CORREÇÃO: Usamos output para controlar os próximos passos
      run: |
        if [[ "${{ github.head_ref }}" == "sentinel/"* ]]; then
           echo "🛑 Loop detectado. Branch de auditoria."
           echo "skip=true" >> "$GITHUB_OUTPUT"
        else
           echo "skip=false" >> "$GITHUB_OUTPUT"
        fi

    # ------------------------------------------------------------------
    # STEP 0.5: PERMISSÕES
    # ------------------------------------------------------------------
    - id: check_perms
      if: steps.circuit_breaker.outputs.skip != 'true'
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
      run: |
        if [ -z "$TOKEN" ]; then
           echo "❌ Token missing."
           exit 1
        fi

    # ------------------------------------------------------------------
    # STEP 1: SCAN
    # ------------------------------------------------------------------
    - id: scan
      if: steps.circuit_breaker.outputs.skip != 'true'
      shell: bash
      env:
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        EXTS: ${{ inputs.file_extensions }}
        EXCLUDE: ${{ inputs.exclude_patterns }}
        REPORT_DIR: ${{ inputs.report_dir }}
      run: |
        set -euo pipefail
        echo "🔎 Scanning..."
        
        # Nome fixo para garantir idempotência
        FILENAME="audit-report.md"
        FULL_PATH="./$REPORT_DIR/$FILENAME"
        mkdir -p "$REPORT_DIR"

        FILES=$(git diff --name-only --diff-filter=ACMRTUXB "$BASE_SHA" "$HEAD_SHA" \
          | grep -E "\.($EXTS)$" \
          | grep -vE "$EXCLUDE" || true)

        if [ -z "$FILES" ]; then
          echo "NO_FILES" > /tmp/scan_status
          echo "0" > /tmp/scan_count
          exit 0
        fi

        PATTERN="\"[^\"]{2,}\"|'[^']{2,}'"
        
        echo "# 🛡️ Code Literal Audit" > "$FULL_PATH"
        echo "> **Data:** $(date -u)" >> "$FULL_PATH"
        echo "" >> "$FULL_PATH"
        echo "\`\`\`text" >> "$FULL_PATH"
        echo "$FILES" | xargs -r grep -HnE "$PATTERN" >> "$FULL_PATH" || true
        echo "\`\`\`" >> "$FULL_PATH"

        COUNT=$(grep -cE "$PATTERN" "$FULL_PATH" || true)
        
        if [ "$COUNT" -gt "0" ]; then
           echo "FOUND" > /tmp/scan_status
           echo "$COUNT" > /tmp/scan_count
           echo "path=$FULL_PATH" >> "$GITHUB_OUTPUT"
        else
           echo "CLEAN" > /tmp/scan_status
           echo "0" > /tmp/scan_count
           rm "$FULL_PATH"
        fi

    # ------------------------------------------------------------------
    # STEP 2: GIT OPS (BRANCH & PR)
    # ------------------------------------------------------------------
    - id: create_pr
      if: steps.circuit_breaker.outputs.skip != 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        REPORT_PATH: ${{ steps.scan.outputs.path }}
        HEAD_REF: ${{ github.head_ref }} # Usando contexto direto é mais seguro
        PR_NUM: ${{ github.event.pull_request.number }}
      run: |
        set -euo pipefail
        
        STATUS=$(cat /tmp/scan_status)
        PR_URL=""
        
        if [ "$STATUS" == "FOUND" ]; then
           git config user.name "sentinel-bot"
           git config user.email "sentinel-bot@users.noreply.github.com"
           
           # Padrão fixo: sentinel/audit/<branch-origem>
           REPORT_BRANCH="sentinel/audit/${HEAD_REF}"
           
           git checkout "$HEAD_REF"
           git checkout -B "$REPORT_BRANCH"
           
           git add "$REPORT_PATH"
           # [skip ci] no commit é vital
           git commit -m "docs(sentinel): update audit report [skip ci]"
           
           git push -f origin "$REPORT_BRANCH"
           
           # Tenta criar PR, ignora se já existe
           gh pr create \
             --base "$HEAD_REF" \
             --head "$REPORT_BRANCH" \
             --title "🛡️ Sentinel Audit: PR #$PR_NUM" \
             --body "Relatório de literais para branch \`$HEAD_REF\`." || true
             
           PR_URL=$(gh pr view "$REPORT_BRANCH" --json url -q .url)
           echo "✅ PR: $PR_URL"
        fi
        
        echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"

    # ------------------------------------------------------------------
    # STEP 3: JSON OUTPUT
    # ------------------------------------------------------------------
    - id: generate_output
      if: steps.circuit_breaker.outputs.skip != 'true'
      shell: bash
      env:
        PR_URL: ${{ steps.create_pr.outputs.pr_url }}
      run: |
        set -euo pipefail
        
        STATUS=$(cat /tmp/scan_status)
        COUNT=$(cat /tmp/scan_count)
        
        if [ "$STATUS" == "FOUND" ]; then
           MSG="Literais detectados ($COUNT)."
           GUIDE="Relatório disponível em: **[Ver PR de Auditoria]($PR_URL)**."
           COLOR="#dbab09"
        elif [ "$STATUS" == "CLEAN" ]; then
           MSG="Código limpo."
           GUIDE="Nenhum literal hardcoded detectado."
           COLOR="#3fb950"
        else
           MSG="Ignorado."
           GUIDE="Sem alterações."
           COLOR="#8b949e"
        fi

        jq -n \
          --arg status "$STATUS" \
          --arg count "$COUNT" \
          --arg msg "$MSG" \
          --arg guide "$GUIDE" \
          --arg url "$PR_URL" \
          --arg color "$COLOR" \
          '{
            analysis: {
              status: $status,
              total_findings: ($count | tonumber),
              report_pr_url: $url
            },
            ui: {
              message: $msg,
              guidance: $guide,
              color: $color
            }
          }' > /tmp/output_payload.json

        JSON_LINE=$(jq -c . /tmp/output_payload.json)
        echo "json_payload=$JSON_LINE" >> "$GITHUB_OUTPUT"
